# Generated by Django 3.2.9 on 2021-12-11 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hangi_asi', models.CharField(blank=True, choices=[('biontech_asi', 'biontech_asi'), ('sinovac_asi', 'sinovac_asi')], max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Belirtiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belirtiler', models.CharField(blank=True, choices=[('siddetli_oksuru', 'siddetli_oksuru'), ('yuksek_ates', 'yuksek_ates'), ('burun_akinti', 'burun_akinti'), ('nefes_darligi', 'nefes_darligi'), ('asiri_halsizlik', 'asiri_halsizlik')], max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hobiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobi1', models.CharField(blank=True, max_length=64, null=True)),
                ('hobi2', models.CharField(blank=True, max_length=64, null=True)),
                ('hobi3', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilaclar', models.TextField()),
                ('hangi_asi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.asi')),
            ],
        ),
        migrations.CreateModel(
            name='Hastalik_Durumu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hastalik_ismi', models.CharField(blank=True, max_length=128, null=True)),
                ('baslangic_tarih', models.DateTimeField(blank=True, help_text='if it happened', null=True)),
                ('belirtiler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.belirtiler')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(blank=True, max_length=64, null=True)),
                ('soyisim', models.CharField(blank=True, max_length=64, null=True)),
                ('tc', models.CharField(blank=True, max_length=64, null=True)),
                ('kan_gurubu', models.CharField(blank=True, max_length=64, null=True)),
                ('dogum_yeri', models.CharField(blank=True, max_length=64, null=True)),
                ('meslek', models.CharField(blank=True, max_length=64, null=True)),
                ('maas', models.IntegerField()),
                ('egitimler', models.CharField(blank=True, choices=[('lisans', 'lisans'), ('yuksek_lisans', 'yuksek_lisans'), ('doktora', 'doktora')], max_length=128, null=True)),
                ('subject', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('hobiler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.hobiler')),
            ],
        ),
        migrations.CreateModel(
            name='Covid_Durumu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslayan_tarih', models.DateTimeField(blank=True, help_text='if it happened', null=True)),
                ('bitis_tarih', models.DateTimeField(blank=True, help_text='if it happened', null=True)),
                ('asi_durumu', models.BooleanField(default=False)),
                ('kronik_mi', models.BooleanField(default=False)),
                ('belirtiler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.belirtiler')),
                ('hangi_asi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.asi')),
                ('temasli_kisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.employee')),
            ],
        ),
    ]
